### ISSUE TITLE
Discuss rule preset for Meteor Guide.

### ISSUE THREAD

**Issue by dferber90** [dferber90/eslint-plugin-meteor#124]
The Meteor guide will likely include ESLint-plugin-Meteor with a rule preset.

**Questions:**
- Different rule presets required for guide of 1.2 and 1.3?
- Which rules should be included in the preset(s) with which configuration?

| Rule | Configuration | Comment |
| --- | --- | --- |
| [audit-argument-checks](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/audit-argument-checks.md) | ["off"] | _Off because it doesn't support destructuring yet_ |
| [eventmap-params](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/eventmap-params.md) | ["error", {"eventParamName": "event", "templateInstanceParamName": "instance"}] |  |
| [no-session](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/no-session.md) | ["error"] |  |
| [no-template-lifecycle-assignments](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/no-template-lifecycle-assignments.md) | ["error"] |  |
| [no-zero-timeout](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/no-zero-timeout.md) | ["error"] |  |
| [prefer-session-equals](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/prefer-session-equals.md) | ["error"] |  |
| [template-names](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/template-names.md) | ["error", "snake-case"] |  |
| [scope-dom-lookups](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/scope-dom-lookups.md) | ["error"] |  |
| [no-dom-lookup-on-created](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/no-dom-lookup-on-created.md) | ["error"] |  |
| [no-template-parent-data](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/rules/no-template-parent-data.md) | ["error"] | _Not mentioned in Meteor Guide_ |

**Comment by stubailo** [comment]
I think we should stick to this as much as humanly possible:

https://github.com/airbnb/javascript

For Meteor 1.2 we might need to omit the stuff about global variables and modules, but for 1.3 I feel like we should be able to use all rules as-is.

**Comment by dferber90** [comment]
Thanks for chiming in. This issue aims to figure out how the rules made available through ESLint-plugin-Meteor should be configured when using the `plugin:meteor/guide` configuration. This is independent of airbnb/javascript.

Providing a configuration for existing ESLint rules and the ones of other plugins (e.g. react) is outside of the scope of this plugin. We could create `eslint-config-meteor` which could extend `eslint-config-airbnb` and include `eslint-plugin-meteor` and `eslint-plugin-react` as dependencies and provide default configurations for them (extend what they export and possibly overwrite some rules).

Currently the configuration exported by this plugin has all rules of the plugin disabled ([source](https://github.com/dferber90/eslint-plugin-meteor/blob/master/lib/index.js#L32)). We should figure out how to configure the rules of this plugin to align with the Meteor guide.

This is my suggestion:

Rule | Configuration
------------ | ------------
[audit-argument-checks](/blob/master/docs/rules/audit-argument-checks.md) |  ["error"]
[eventmap-params](/blob/master/docs/rules/eventmap-params.md) | ["error", {"eventParamName": "event", "templateInstanceParamName": "instance"}]
[no-session](/blob/master/docs/rules/no-session.md) | ["error"]
[no-template-lifecycle-assignments](/blob/master/docs/rules/no-template-lifecycle-assignments.md) | ["error"]
[no-zero-timeout](/blob/master/docs/rules/no-zero-timeout.md) | ["error"]
[prefer-session-equals](/blob/master/docs/rules/prefer-session-equals.md) | ["error"]
[template-names](/blob/master/docs/rules/template-names.md) | ["error", "snake-case"]

As there are not that many rules exported by this plugin at the moment, this is fairly simple at the moment.

**Comment by stubailo** [comment]
Ohhhhhh I see. I completely misunderstood what was going on.

the links in that chart are broken, BTW. I'd want to check them out.

**Comment by dferber90** [comment]
I thought so :-) The ESLint ecosystem works like this (as far as I understand it):
- plugins provide sets of rules and can have recommended configurations for their own rules (and also enable environments like meteor or jquery and special parser settings like JSX support). Examples are eslint-plugin-meteor and eslint-plugin-react
- configs configure the rules provided by ESLint itself. They can further contain plugins and provide default rules for them as well.

So the end goal would be to create eslint-config-meteor which would extend eslint-config-airbnb and contain eslint-plugin-react and eslint-plugin-meteor. Developers then only need to `npm i eslint-config-meteor` and enable only this config in their `.eslintrc`, which would pull in the other dependencies as well.

---
I fixed the links. Those are the docs for the rules. Check out the `docs` folder in the repo.

**Comment by stubailo** [comment]
So I'm starting to become unhappy with audit argument checks, because I really want to use keyword arguments for everything: "Support immediate destructuring of params" in your docs.

The other ones look good to me. We could add a lot more for the guide as well.

**Comment by dferber90** [comment]
> So I'm starting to become unhappy with audit argument checks, because I really want to use keyword arguments for everything: "Support immediate destructuring of params" in your docs.

Yes, I know about that and I can see how it is annoying. This is technically possible, but I haven't put in the time yet and I'm not sure I will. Statically analyzing this gets complicated when renames happen during the destructuring or when the destructuring is nested.

I agree that we should disable rules with false warnings for the default configuration. I'll move the table to the top comment and keep it updated there.

> We could add a lot more for the guide as well.

Creating one rule currently takes me about 4 hours with writing docs, tests and so on. Happy to accept lots of PRs though :P

**Comment by tmeasday** [comment]
I think these choices are all great as far as I'm concerned.

**Comment by zimme** [comment]
I think exceptions for `Match.OneOf` etc is needed with http://eslint.org/docs/rules/new-cap rule also.
