### ISSUE TITLE
Support modules

### ISSUE THREAD

**Issue by dferber90** [dferber90/eslint-plugin-meteor#125]
Meteor 1.3 supports modules. This means variables may be renamed during the import.
Should the plugin support this? Or should we require all variables to have their default name?

Example:

``` js
import Session from 'meteor/session'

// vs

import X from 'meteor/session'
```

or for non-default exports:

``` js
import { Blaze } from 'meteor/blaze'

// vs

import { Blaze as B } from 'meteor/blaze';
```

**Comment by talha-asad** [comment]
Of course the plugin should support this.

**Comment by dferber90** [comment]
This question is more along the lines of whether it's worth the added conpexity and added development time for new rules, not the technical aspect of it

**Comment by ThomasCrevoisier** [comment]
Specifying this in the ESLint config should do the trick nope ? 
https://gist.github.com/ThomasCrevoisier/0ccf10961fb7715bbdf67bb8464be430

**Comment by dferber90** [comment]
@ThomasCrevoisier This works already.

The issue is that previously Meteor provided globals (e.g. `Meteor`, `Session`) which didn't have to be imported and always had the same name.

Now, with ES modules somebody could do `import Sess from 'meteor/session'` and then the rules will stop working for `Sess` because `eslint-plugin-meteor` doesn't know it should check `Sess`.

As long as people keep the default names things still work. So far there hasn't been an issue of somebody reporting he needs to be able to use renamed variables.

**Comment by ThomasCrevoisier** [comment]
@dferber90 Okay my bad, I didn't fully understand the problem here. Thanks for the explanation.

**Comment by dferber90** [comment]
Decided not to support it for now.
