### ISSUE TITLE
eventmap-params won't consider destructuring

### ISSUE THREAD

**Issue by runarberg** [dferber90/eslint-plugin-meteor#200]
Destructuring parameters in event-map methods will yield `eventmap-params` error. For example the following will fail:

```js
Template.foo.events({
  'change input[data-action="bar"]'({ target }, { findAll }) {
    findAll('input[data-action="baz"]').forEach(input => {
      input.checked = target.checked;
    });
  },
});
```

Is this intended, and we shuldn't destructure our event-maps, or is this something that hasn't been implemented yet?

**Comment by dferber90** [comment]
Thanks for reporting. This hasn't been implemented yet. Maybe you want to give it a try? :)

**Comment by runarberg** [comment]
Sure, I'll send in a PR this afternoon

**Comment by dferber90** [comment]
Awesome!

Please ensure your PR also adds the relevant tests and follows the [commit messages convention](https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md). Thanks :)
