### ISSUE TITLE
Issue about basic set up

### ISSUE THREAD

**Issue by taoning2014** [dferber90/eslint-plugin-meteor#202]
In your guide, you specify the basic set up should be:

`{
  "plugins": [
    "meteor"
  ],
  "extends": [
    "plugin:meteor/recommended"
  ]
}`

If the user follow these setup, 'Template' will still be 'no-undef'. To fix it, user need to manually add 'meteor' as 'env'. So why not specify it here? Or a better solution maybe put that(put 'meteor' in 'env') in 'meteor/recommended' file, so that when user extends that, they will got everything right to work.

**Comment by dferber90** [comment]
Thank you for the report :-)

Are you talking about [this guide](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/guides/setup.md)? The guide mentions the env-stuff directly under it in the Tips section.

> If the user follow these setup, 'Template' will still be 'no-undef'

By default all rules are disabled in ESLint. `no-undef` is disabled as well.
This means to get the warning the user would have to enable `no-undef` first.

>  Or a better solution maybe put that(put 'meteor' in 'env') in 'meteor/recommended' file,

Plugins should only configure their own rules from their recommended settings. The correct solution would be to create a [Shareable Config](http://eslint.org/docs/developer-guide/shareable-configs) which contains `eslint-plugin-meteor`, sets the recommended rules and also sets the Meteor env (and eventually enables some other rules). Enabling the Meteor Environment is not a concern of `eslint-plugin-meteor`.

**Comment by taoning2014** [comment]
Got it, thanks for asking my questions as well as write/maintain this useful package. : )
