### ISSUE TITLE
Docs missing

### ISSUE THREAD

**Issue by AnthonyAstige** [dferber90/eslint-plugin-meteor#209]
https://github.com/dferber90/eslint-plugin-meteor has a couple of broken links under [Best Practices](https://github.com/dferber90/eslint-plugin-meteor#best-practices)

* Session
     * [prefer-session-equals](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/prefer-session-equals.md)
* Blaze
     * [template-names](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/template-names.md)

**Comment by dferber90** [comment]
Thanks for pointing it out 👍
