### ISSUE TITLE
triggers error in eslint-plugin-import in Meteor 1.3.4.1

### ISSUE THREAD

**Issue by rhettlivingston** [dferber90/eslint-plugin-meteor#269]
I have been trying to update the meteor/todos application to 1.3.4.1. After doing so, I encountered problems with eslint-plugin-import crashing. The crash doesn't start until after wiping out node-modules and running a fresh npm install with npm 3.9.6 and node 0.10.45 (the versions included in Meteor 1.3.4.1). 

It has now been narrowed down to some type of interaction between eslint-plugin-import and eslint-plugin-meteor. To narrow it down, I created a very simple duplication scenario outside of the meteor environment as shown in [this comment](https://github.com/benmosher/eslint-plugin-import/issues/415#issuecomment-230556060) in the issue benmosher/eslint-plugin-import#415.

As explained in the [comment that follows that one](https://github.com/benmosher/eslint-plugin-import/issues/415#issuecomment-230564890), disabling eslint-plugin-meteor prevents their crash. 

Their crash seems to be in some es6 code. Could it be getting triggered by some clash in your usage of babel?

**Comment by dferber90** [comment]
Possibly resolved in https://github.com/benmosher/eslint-plugin-import/pull/419 :)

**Comment by rhettlivingston** [comment]
Yes, all my testing indicates that the workaround of simply dropping all es6-symbol usage on their side will eliminate the immediate problem as soon as they release the patch. 

Truthfully, we never really figured the problem out. We just came up with a way to punt. I think it may have been more on their side in that the means by which they employed es6-symbol seemed to have warnings associated with it in the README for that package. In any case, let's consider it closed and hope that we don't see it again in some other flavor.
