### ISSUE TITLE
Rule idea: disallow async-await function in server-side code.

### ISSUE THREAD

**Issue by dikmax** [dferber90/eslint-plugin-meteor#281]
While async-await functions are quite handy on the client side, their usage could bring unexpected behavior to server-side code.

**Comment by dferber90** [comment]
Thanks for the suggestions :)

We don't know whether code is going to run on the server or on the client, so this is not possible 
with the current architecture. I want to keep that complexity out of the plugin.

See https://github.com/dferber90/eslint-plugin-meteor/issues/259#issuecomment-228960339 for a more detailed explanation.
