### ISSUE TITLE
Module fails to install via npm: shasum check failed

### ISSUE THREAD

**Issue by johanbrook** [dferber90/eslint-plugin-meteor#30]
I run this

```
npm install --save-dev eslint-plugin-meteor
```

and get this

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "eslint-plugin-meteor"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6

npm ERR! shasum check failed for /var/folders/v9/tw72bsl9245ckv_zd3nmtwwm0000gn/T/npm-88441-a142f354/registry.npmjs.org/eslint-plugin-meteor/-/eslint-plugin-meteor-0.9.1.tgz
npm ERR! Expected: 528b20cf23b0b5e616e6e24b432d949dcd09a0b0
npm ERR! Actual:   3ac06bb31b4fc1dbfbcfbe52d214aae91128cd9b
npm ERR! From:     http://registry.npmjs.org/eslint-plugin-meteor/-/eslint-plugin-meteor-0.9.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Johan/Projects/Code/lookback/lookback/npm-debug.log
```

Is something off with this module's npm publish? I noticed there were not `version` field in `package.json`. 

A google search on the error suggested `npm cache clean` and upgrading node/npm, which I've done to no avail.

**Comment by dferber90** [comment]
Thanks for reporting. I have been notified about this error already by @PhilippSpo. It should be fine if you use version 0.9.0. The issue will be resolved with the next release.

There is no version field in `package.json` because the whole publication process is automated with the excellent https://github.com/semantic-release/semantic-release.

**Comment by dferber90** [comment]
I've just pushed a new release which is essentially the same thing as 0.9.1 but with a new version number. Let me know how that works for you.

Sorry for the inconvenience!

**Comment by johanbrook** [comment]
Works out of the box! Thanks! :+1:
