### ISSUE TITLE
Error while loading rule 'meteor/core': Path must be a string. Received false

### ISSUE THREAD

**Issue by johanbrook** [dferber90/eslint-plugin-meteor#31]
Hi!

When running `eslint .` in my project, this is dumped:

```
TypeError: Error while loading rule 'meteor/core': Path must be a string. Received false
    at assertPath (path.js:8:11)
    at Object.posix.normalize (path.js:450:3)
    at stripPathPrefix (/Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint-plugin-meteor/dist/util/internal/stripPathPrefix.js:24:44)
    at exports.default (/Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint-plugin-meteor/dist/util/internal/getRelativePath.js:17:43)
    at exports.default (/Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint-plugin-meteor/dist/util/getMeta.js:17:50)
    at /Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint-plugin-meteor/dist/rules/core.js:20:20
    at /Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint/lib/eslint.js:707:28
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint/lib/eslint.js:686:16)
    at processText (/Users/Johan/Projects/Code/lookback/lookback/node_modules/eslint/lib/cli-engine.js:221:27)
```

I did some basic tracing, and it seems `stripPathPrefix` is called with `(false, "path/to/file.js")` for a particular file path of mine (!). This is reproducable for me every time:

I added this to `stripPathPrefix`:

```
console.log(parent);
console.log(child);
console.log('******');
```

And this was logged:

```
******
/path/to/project/app
/path/to/project/app/server/templates/_email-templates.js
*******
/path/to/project/app
/path/to/project/app/server/templates/_email-templates.js
*******
false
/path/to/project/environments/build/velocity.js

// Here it throws the error:
TypeError: Error while loading rule 'meteor/core': Path must be a string. Received false
...
```

It seems `getRelativePath` is calling the function with `false` as parent for this particular file path; i.e. `getRootPath` is returning false in some cases. 

Thanks!

**Comment by dferber90** [comment]
Thanks for the detailed report! I'm currently rewriting the internals.

For the linter to work, it must be able to figure out the location of a file relative to the Meteor project root directory because that determines the environment the file runs in. To do this, the plugin starts with the name of the file being linted and searches the path upwards until a folder is found that contains `.meteor/release`. Is the `velocity.js` file in the Meteor project?

`getRootPath` also caches directories so the file system has to be used only once most of the time which speeds the plugin up. It looks like `getRootPath` is not able to figure out the location of the Meteor project.

The plugin should not fail in such situations but simply report no errors for such files, so it's definitely a bug. I'll look into it in a few hours.

**Comment by johanbrook** [comment]
Thanks for the quick reply! 

Right, I see. This file is outside of the Meteor app, but inside the project folder (i.e. one level above the Meteor app), so I totally get the part about it not picking up `.meteor/release`.

> getRootPath also caches directories so the file system has to be used only once most of the time which speeds the plugin up.

Is it possible to clean that cache somehow?

> The plugin should not fail in such situations but simply report no errors for such files, so it's definitely a bug.

Yeah, I think non-Meteor files simply should be ignored, since I think it's quite common for people to simply run `eslint .` in their root directory – may it be a Meteor app or a plain dir.

**Comment by dferber90** [comment]
> Is it possible to clean that cache somehow?

The cache is only kept during the execution of ESLint. It is a variable that holds paths while running `eslint .`. Each invocation gets a fresh cache. If you're using the linter in Atom, hit  `View > Reload` to reload Atom, which reloads the plugins and therefore empties the cache.

> Yeah, I think non-Meteor files simply should be ignored, since I think it's quite common for people to simply run eslint . in their root directory – may it be a Meteor app or a plain dir.

I tried to account for that situation, but looks like I messed up 😓 Fix is coming this evening.

**Comment by johanbrook** [comment]
> Each invocation gets a fresh cache. If you're using the linter in Atom, hit View > Reload to reload Atom, which reloads the plugins and therefore empties the cache.

Gotcha :+1: 

> I tried to account for that situation, but looks like I messed up 😓 Fix is coming this evening.

No worries, keep it up! :)

**Comment by dferber90** [comment]
Let me know whether 0.9.3 works for you or not. I could not reproduce the error so I'm kind of in the dark here.

Are you using a globally installed version of the plugin and eslint?

**Comment by johanbrook** [comment]
Works for me after updating to 0.9.3!

I was using a local install of ESLint and this plugin.
