### ISSUE TITLE
Support Foo_bar template naming

### ISSUE THREAD

**Issue by athyuttamre** [dferber90/eslint-plugin-meteor#323]
`Foo_bar` style is what the Meteor Guide recommends for naming templates. The template name rule does not support this. Would be great to add it as an option!

**Comment by athyuttamre** [comment]
Specifically the first word starts with a capital letter.

**Comment by dferber90** [comment]
I think this may be possible already using confit options. But maybe I removed it again because there was no clear set of rules for this style. Happy to accept a PR if this turns out to be missing.

*I'm backpacking for another week so I can't really look myself.*

**Comment by dferber90** [comment]
The just released version `4.1.0` supports the `upper-snake-case` option to the `template-names` rule.
