### ISSUE TITLE
Rule Update Proposal: Allow un-scoped $ when argument matches a regex or whitelist

### ISSUE THREAD

**Issue by AnthonyReid99** [dferber90/eslint-plugin-meteor#344]
I like the 'scope-dom-lookups' rule for when I'm actually querying the DOM, but I often use the $ function to convert my 'event.currentTarget' to a jquery node. In that case it seems unnecessary to require the scoped template.$.

**Comment by dferber90** [comment]
Thanks for getting in touch. I like the suggestion, but I think the implementation is not straightforward.

Do I understand this correctly, you want to


```js
$(event.currentTarget) // allow this
$('div') // forbid this
```

I have a few concerns with this:

##### How would the whitelist work

What would be in the whitelist? The variable name of `event` could be anything. We never know whether it is a string or a node. Would the whitelist work based on the variable name?

##### Is it worth it
Is it worth going through the trouble of implementing this and the additional configuration when you can just use `template.$`? Or possibly `// eslint-disable-next-line scope-dom-lookups`, although that is way more typing.
