### ISSUE TITLE
Error: Cannot read property 'recommended' of undefined (Atom)

### ISSUE THREAD

**Issue by jhuenges** [dferber90/eslint-plugin-meteor#392]
Hey, I am trying to setup linting for my meteor project. I followed the guide and added 
```js
"plugins": [ "meteor" ],
"extends": [ "airbnb", "plugin:meteor/recommended"  ],
"settings": {
  "import/resolver": "meteor"
 },
 "rules": {}
```
to my eslint config. However, when I am linting a file I get the following error message:
![image](https://cloud.githubusercontent.com/assets/7192165/20013121/4d4e1120-a2b2-11e6-9979-46cdef5c757f.png)

Do you have any idea on how to solve this?

**Comment by dferber90** [comment]
Did you figure it out in the meantime?

Maybe you forgot to run `npm install eslint-plugin-meteor`?

**Comment by jhuenges** [comment]
No, I didnt :(

`eslint-plugin-meteor` is installed:
![image](https://cloud.githubusercontent.com/assets/7192165/20059589/3d7b8efc-a4f7-11e6-809b-39c3629872bc.png)

I will try to install everything globally next

**Comment by dferber90** [comment]
That seems okay except for `eslint-plugin-import`.

Can you try to resolve the `peer invalid` issue?
Which node version are you using?

It's hard to provide help with that little context. As you seem to be the only one facing this problem it looks like something is wrong with your setup.

**Comment by dferber90** [comment]
This seems to work for everybody else. Closing.
