### ISSUE TITLE
Async arrow functions

### ISSUE THREAD

**Issue by icetee** [dferber90/eslint-plugin-meteor#468]
Hi,

how to allow async arrow function in this plugin without [babel-eslint](https://github.com/babel/babel-eslint/issues/319)?

```
(async () => {
    console.log(await asyncFunction());
})();
```

**Comment by dferber90** [comment]
This is not something related to `eslint-plugin-meteor`, but to `eslint` in general unless you saw it breaking when adding `eslint-plugin-meteor` to your existing `eslint` setup.

Maybe this helps: https://github.com/eslint/eslint/issues/1657
