### ISSUE TITLE
CLI and Sublime Text integration

### ISSUE THREAD

**Issue by mquandalle** [dferber90/eslint-plugin-meteor#49]
I recently merged your PR https://github.com/wekan/wekan/pull/370. Even if I like Atom, my editor of choice is still Sublime Text and I was unable to get the new linting plugins work in there. It might be related to the fact that `eslint ./` doesn’t work either on the CLI:

```
➜  wekan git:(devel) npm install        
[...]
➜  wekan git:(devel) eslint ./          
module.js:338
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/eslint-plugin-meteor/dist/index.js:3:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Maybe it’s a problem with Eslint or with one of the plugin used, but I wanted to ask you @dferber90 first before reporting an issue elsewhere. I’m on Ubuntu 15.04, I have installed the `devDependencies` locally and I have also the following versions installed globally:

```
$ node --version
v4.0.0
$ npm --version
2.14.2
$ eslint --version
v1.7.3
```

**Comment by dferber90** [comment]
Thanks for the report!

>  It might be related to the fact that eslint ./ doesn’t work either on the CLI:

This is intended behavior. As `eslint` and `eslint-plugin-meteor` are no longer installed globally, you can't use them directly. Instead use `$ npm run lint`, or `$ npm test`. Let me know if it works for you with this command.

The reason it throws for you is because running `eslint ./` will run the globally installed version instead of the local one. And this global version had a bug where I added `babel-runtime` as a devDependency instead of a normal one. If you update the globally installed version it should work again.
But using the local version is preferred, so you can remove the global versions to be sure to always use the local ones.


> Even if I like Atom, my editor of choice is still Sublime Text 

It should work just fine in ST. That was my previous editor. Make sure to configure it to use the local versions of ESLint if it finds them.  Here's some [details](https://github.com/roadhump/SublimeLinter-eslint#faq-and-troubleshooting).

Let me know if something is unclear still 😊

**Comment by mquandalle** [comment]
The actual Sublime Text linter error is:

> Error: ESLint crashed: Error while loading rule 'meteor.globals': Invariant Violation: Linted file is not in parent.

**Comment by dferber90** [comment]
Oh, looks like [SublimeLinter](https://github.com/roadhump/SublimeLinter-eslint) does not pass the filename to ESLint (of the file being linted). ESLint-plugin-Meteor relies on it to determine where a file is going to run. When they add that, then it should work.

**Comment by dferber90** [comment]
Actually SublimeLinter passes the relative filename instead of the absolute one.
This seems to be the fix https://github.com/roadhump/SublimeLinter-eslint#contextgetfilename-in-rule-returns-relative-path

Maybe ESLint-plugin-Meteor can be extended to accept relative paths as well.

**Comment by mquandalle** [comment]
Yes that fixed the issue :)

**Comment by mquandalle** [comment]
I guess that would be good to document — both here and on Wekan contributor guide.

**Comment by dferber90** [comment]
As I understand it, setting this option breaks support of `.eslintignore` in Sublime Text. I have added support for relative file paths instead. After updating to the newest release, you'll be able to use Sublime Text without any issues (hopefully). You can remove that fix with the extra settings again then :)

This way it just works out-of-the-box for everybody hopefully.

**Comment by mquandalle** [comment]
Yep, it works! I’m far more happy with this solution :-)

**Comment by mquandalle** [comment]
About Greenkeeper, I didn’t now it until I saw it in your project. I guess the first step to make it valuable would be to add some tests to wekan :-) I also like to read the changelog (and not only the commit history before merging). And anyway almost all Wekan dependencies are actually meteor packages so Greenkeeper wouldn’t help — but a Greenkeeper for Meteor packages would be great!

**Comment by dferber90** [comment]
> I also like to read the changelog

There's nothing stopping you from doing it. It just sends a PR, so you know there's been a new version. It doesn't auto-merge or anything :)

**Comment by mquandalle** [comment]
Yes of course :-) (but sending the changelog directly in the PR would be a great improvement!)
