### ISSUE TITLE
audit-argument-checks with SimpleSchema

### ISSUE THREAD

**Issue by cryve** [dferber90/eslint-plugin-meteor#496]
Thank you @dferber90 for this great plugin, it really improved my Meteor coding experience in Atom!

Only issue with the default rules preset is that 'audit-argument-checks' expects the use of 'check', however, I use SimpleSchema and so does the Meteor Guide propose (https://guide.meteor.com/data-loading.html#publications). 

Detecting SimpleSchema argument validation would be a nice feature for this rule. Projects using SimpleSchema could spare another validation package.
This has already been requested here: https://forums.meteor.com/t/publications-and-data-loading/19661/2

**Comment by dferber90** [comment]
Thanks for the kind words. Technically, it should be possible to extend the rule to a certain degree. Not sure it could catch all cases. It definitely seems like a bit of work.

I'd accept a PR implementing this. I won't implement it myself though. For now I'd recommend turning the rule off manually in your configuration.
