### ISSUE TITLE
Update deps for latest eslint

### ISSUE THREAD

**Issue by hexsprite** [dferber90/eslint-plugin-meteor#507]
Just upgraded to latest eslint 4.1.0

Getting:

`warning "eslint-plugin-meteor@4.0.1" has incorrect peer dependency "eslint@^3.7.0".`

**Comment by DanielDornhardt** [comment]
Hi @hexsprite , why did you close this? I'm trying to get started with linting too for a meteor project and ran into the exact same problem / message. Did you manage to fix this?

**Comment by dferber90** [comment]
Sounds like I need to release. In case it works with `eslint@4` it's okay to ignore the warning.

From the [Migrating to v4.0.0](http://eslint.org/docs/user-guide/migrating-to-4.0.0) page it looks like there are no breaking changes affecting eslint-plugin-meteor.

**Comment by dferber90** [comment]
Can you upgrade to `eslint-plugin-meteor@next` and see whether that resolved the issue?

**Comment by hexsprite** [comment]
Still getting a warning for some reason.

```
$ meteor npm i -D eslint-plugin-meteor@next
npm WARN eslint-plugin-meteor@4.0.1 requires a peer of eslint@^3.7.0 but none was installed.
```

**Comment by dferber90** [comment]
I tried it out in my test project and I'm still not seeing the issue.
