### ISSUE TITLE
Eslint Broken after upgrading to 4.1.1

### ISSUE THREAD

**Issue by joncursi** [dferber90/eslint-plugin-meteor#521]
After upgrading to 4.1.1, my ESLint stopped linting errors altogether in Atom. Any ideas why?

**Comment by joncursi** [comment]
Downgrading to 4.1.0 gets ESLint operational again for me. So something is up in the latest release, at least on my end with Atom!

**Comment by dferber90** [comment]
Thanks for the information. I'm about to go on holidays for a week, so it might be a bit until I can get to this. Did you restart Atom after upgrading ESLint?

I haven't tried reproducing this myself so far. I'm not working on a Meteor project at the moment, so I'm not using the plugin myself anymore :/

**Comment by philcruz** [comment]
I'm hitting the same issue.

**Comment by dferber90** [comment]
I can confirm that the latest release is broken. The release process is broken. Working on a fix now.

**Comment by dferber90** [comment]
Thanks everybody for pointing this out. The release process was broken (it was using npm v3, but relying on `prepublishOnly`, which is a npm v4 feature). Upgraded npm to v5.3 on CI to resolve the issue in #529.

The release `v4.1.4` contains the fix and should work again. Moving the `latest` tag to it now.
