### ISSUE TITLE
audit-argument-checks in return statements

### ISSUE THREAD

**Issue by Floriferous** [dferber90/eslint-plugin-meteor#543]
Edit: made the issue broader because it happens with all functions, if check is used in the return value.

I wouldn't expect audit-argument-checks to complain in these functions:

```js
// Error: "id" is not checked
Meteor.method({
  doSomething: id => check(id, String) && doSomethingWith(id),
  doSomethingElse(id) {
    return check(id, String) && doSomethingWith(id);
  },
})
```

Is this the correct behavior?

**Comment by dferber90** [comment]
Technically it gets checked, but for example when you do `return doSomethingWith(id) && check(id, String)` it will not get checked in case `doSomethingWith` returns false.

So if we were to make the rule support this, it would only be able to support it when the first one is it. I'm not sure it's worth the effort.

**Comment by Floriferous** [comment]
Fair point, I can live with a few warnings in that case!

**Comment by dferber90** [comment]
Could you not just do this:

```js
  doSomethingElse(id) {
    check(id, String)
    return doSomethingWith(id);
  },
```

Or does the code rely on the return value of `check`? As far as I understand [the docs](https://docs.meteor.com/api/check.html#check) `check` will throw if it does not match. So moving it up would result in the same behaviour.

**Comment by dferber90** [comment]
So you would not have any warnings, right?

**Comment by Floriferous** [comment]
Yes, you're completely right, but I have a file where this construct (single id, single function call) repeats itself a lot. So I'd rather go for a super-clean and readable one-liner instead of 4 lines for each call.
