### ISSUE TITLE
Incorrect meteor/audit-argument-checks message

### ISSUE THREAD

**Issue by Liiva** [dferber90/eslint-plugin-meteor#619]
The following code snippet from [documentation of Meteor's email API.](https://docs.meteor.com/api/email.html) gives a `ESLint: "<param>" is not checked` for each of the parameters.
```
Meteor.methods({
  sendEmail(to, from, subject, text) {
    // Make sure that all arguments are strings.
    check([to, from, subject, text], [String]);

    // Let other method calls from the same client start running, without
    // waiting for the email sending to complete.
    this.unblock();

    Email.send({ to, from, subject, text });
  }
});
```

**Comment by dferber90** [comment]
Thanks for the report! I fixed this now in #620 and it will be out with the next release.

This fix is now published as v4.2.0.
