### ISSUE TITLE
Publish 4.2.1 to npm

### ISSUE THREAD

**Issue by xavierpriour** [dferber90/eslint-plugin-meteor#645]
Hi @dferber90 ,

Thanks for all your work on `eslint-plugin-meteor`, it's very helpful!

You published 4.2.1 here on github a while ago, but it's not on npm, so `npm update` and `npm outdated` do not pick it up.

Could you push it to npm as well? Or is there a reason you're holding on to it?

thanks again

**Comment by dferber90** [comment]
Is anything on version 4.2.0 not working for you?

`eslint-plugin-meteor` uses distribution channels. The main version is still at 4.2.0, but if you install `eslint-plugin-meteor@next` you'd get the newest version (4.2.1). You can also install 4.2.1 by specifying that version in your `package.json` directly. Version 4.2.1 is indeed published to npm, it's just not specified as the `latest` release.

4.2.1 only includes an update of a dependency over 4.2.0. I didn't want to publish a new release for this minor fix as it would mean users of this package would need to upgrade without really getting any value out of it. So I didn't move the `latest` tag up to avoid unnecessary work for the users of this package.

**Comment by xavierpriour** [comment]
wow, that was fast :) congrats!

My "issue" is I'm trying to make `npm outdated` happy and reporting a nice empty list:

If I install 4.2.1, it reports I'm beyond latest:
```
➜  meteor npm outdated
Package               Current  Wanted  Latest  Location
eslint-plugin-meteor    4.2.1   4.2.1   4.2.0  datanimist
```

If I stay on 4.2.0, it tells me I want 4.2.1:
```
➜ meteor npm outdated
Package               Current  Wanted  Latest  Location
eslint-plugin-meteor    4.2.0   4.2.1   4.2.0  datanimist
```

I would have loved to get rid of that, but if I can't it's not a big deal :grin:

**Comment by dferber90** [comment]
This seems to just be the way `npm outdated` works when dealing with packages that use dist-tags. Doesn't seem like anything we need to do anything about this.

I'll soon publish `v5` which is going to be the latest release, so this will make `npm outdated` for a while... until a new `next` version comes along :P
