### ISSUE TITLE
Should babel-register be a dev-dependency instead of dependency?

### ISSUE THREAD

**Issue by nathan-muir** [dferber90/eslint-plugin-meteor#654]
Hi, 

Just noticed after updating meteor to 1.7-rc.3, which uses the new babel runtime package (`@babel/runtime@^7.0.0-beta.46`), that `eslint-plugin-meteor` was still depending on `babel-register` / `babel-runtime` @ `6.26`

Compared with other plugins, I'm guessing that `babel-register` shouldn't be under `dependencies`, but belongs under `devDependencies` instead.

eg. https://github.com/3stack-software/eslint-plugin-meteor/commit/dd53fe1bbe9b14e10adfcaafe39af0d36e51c8f4

**Comment by nathan-muir** [comment]
Ah, no.  There's still a bit of code dependent on the `babel-runtime`, as you're using `"transform-runtime"` in `.babelrc`..

**Comment by dferber90** [comment]
I completely removed `babel` as a dependency in `5.0.0`. Let me know how that works for you. I went ahead and tried it myself and all seemed to work nicely.

Note: `eslint-plugin-meteor` now needs at least `node@6`, which is the current minimal LTS version.

**Comment by nathan-muir** [comment]
Works great @dferber90, Cheers!
