### ISSUE TITLE
ESLint 5.X

### ISSUE THREAD

**Issue by THETCR** [dferber90/eslint-plugin-meteor#680]
Since ESLint 5 has been released all other plugins used in Meteor projects have been updated. Is there any ETA in sight when this project will support ESLint 5?

**Comment by dferber90** [comment]
There are some problems with CI currently which I'd need to look into first. Thanks a ton for your PR. I'll try to take a look today!

**Comment by dferber90** [comment]
Thanks a ton for your PR.

It has been released as `5.1.0`. Could you try upgrading to that version and report back whether it solved the problems you were seeing? If so, I'll move the `latest` tag along and thereby make the release official :)

**Comment by dferber90** [comment]
I tested it manually now and it worked. I'll move the `latest` tag along. Thanks a ton for your PR!
