### ISSUE TITLE
`no-session` is too strict

### ISSUE THREAD

**Issue by quarterto** [dferber90/eslint-plugin-meteor#719]
The `no-session` rule is applying for any variable called `Session`, whether it's from `meteor/session` or not. I have a collection called `Session`, which this rule is marking as an error.

**Comment by dferber90** [comment]
Thanks for reaching out. This is a known issue and not something I plan on adding as it increases complexity. This is somewhat related to https://github.com/dferber90/eslint-plugin-meteor/issues/125#issuecomment-203865388.

If you're up for it you can open a PR, but it would (from the top of my head):
- have to support old Meteor versions where `Session` was a global
- support `import X from "meteor/session"`
- support `const X = require("meteor/session")`
- support `let X = await import("meteor/session");`

I'm not going to add this myself as I'm not using Meteor anymore. Thats also why I'm not sure how to best add it. Maybe it's good enough to disable this rule in your case?

**Comment by quarterto** [comment]
yikes, that does sound complex. i've disabled the rule anyway. thanks!
