### ISSUE TITLE
Dependency warning with eslint 6

### ISSUE THREAD

**Issue by rj-david** [dferber90/eslint-plugin-meteor#729]
Eslint 6 has been released and this package has dependency warning with it

**Comment by dferber90** [comment]
@rj-david Cool, wanna open a PR with the upgrade?

**Comment by dferber90** [comment]
https://github.com/dferber90/eslint-plugin-meteor/pull/727 is open, but there are some issues that need to be addressed.

**Comment by dferber90** [comment]
This is fixed in 6.0.0 which has been released now.
