### ISSUE TITLE
TypeError: pluginNames.forEach is not a function

### ISSUE THREAD

**Issue by roberto68** [dferber90/eslint-plugin-meteor#77]
[eslintrc.txt](https://github.com/dferber90/eslint-plugin-meteor/files/37106/eslintrc.txt)

 npm run lint

> getin-react@1.0.0 lint /home/robert/.meteor/getin-react
> eslint .

/home/robert/.meteor/getin-react/node_modules/eslint/lib/config.js:239
    pluginNames.forEach(function(pluginName) {
                ^

TypeError: pluginNames.forEach is not a function
    at getPluginsConfig (/home/robert/.meteor/getin-react/node_modules/eslint/lib/config.js:239:17)
    at Config.getConfig (/home/robert/.meteor/getin-react/node_modules/eslint/lib/config.js:457:24)
    at processText (/home/robert/.meteor/getin-react/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/home/robert/.meteor/getin-react/node_modules/eslint/lib/cli-engine.js:262:18)
    at executeOnFile (/home/robert/.meteor/getin-react/node_modules/eslint/lib/cli-engine.js:609:23)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/home/robert/.meteor/getin-react/node_modules/eslint/lib/cli-engine.js:632:56)
    at Object.cli.execute (/home/robert/.meteor/getin-react/node_modules/eslint/lib/cli.js:161:95)
    at Object.<anonymous> (/home/robert/.meteor/getin-react/node_modules/eslint/bin/eslint.js:61:20)
    at Module._compile (module.js:434:26)

npm ERR! Linux 4.2.5-300.fc23.x86_64
npm ERR! argv "/home/robert/.nvm/versions/node/v4.0.0/bin/node" "/home/robert/.nvm/versions/node/v4.0.0/bin/npm" "run" "lint"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! getin-react@1.0.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getin-react@1.0.0 lint script 'eslint .'.
npm ERR! This is most likely a problem with the getin-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get their info via:
npm ERR!     npm owner ls getin-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robert/.meteor/getin-react/npm-debug.log

**Comment by roberto68** [comment]
eslint problem kinda solved. problem was with naming my plugins: further info https://github.com/eslint/eslint/issues/4469
When I run npm run lint I don not get any errors but:

> getin-react@1.0.0 lint /home/robert/.meteor/getin-react
> eslint .

The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.

/home/robert/.meteor/getin-react/packages/npm-container/index.js
  1:1   error  "Meteor" is not defined                              no-undef
  2:3   error  Expected indentation of 1 tab character but found 0  indent
  2:16  error  "Npm" is not defined                                 no-undef
  3:3   error  Expected indentation of 1 tab character but found 0  indent
  6:1   error  "Meteor" is not defined                              no-undef
  7:3   error  Expected indentation of 1 tab character but found 0  indent
  7:3   error  Unexpected console statement                         no-console
  7:16  error  Strings must use doublequote                         quotes
  8:3   error  Expected indentation of 1 tab character but found 0  indent
  8:10  error  "Meteor" is not defined                              no-undef

/home/robert/.meteor/getin-react/packages/npm-container/package.js
   1:24  error  Strings must use doublequote                         quotes
   2:22  error  Strings must use doublequote                         quotes
   5:3   error  Expected indentation of 1 tab character but found 0  indent
   5:12  error  Strings must use doublequote                         quotes
   6:3   error  Expected indentation of 1 tab character but found 0  indent
   6:12  error  Strings must use doublequote                         quotes
   7:3   error  Expected indentation of 1 tab character but found 0  indent
   7:9   error  Strings must use doublequote                         quotes
  10:37  error  Strings must use doublequote                         quotes
  12:3   error  Expected indentation of 1 tab character but found 0  indent
  13:3   error  Expected indentation of 1 tab character but found 0  indent
  14:3   error  Expected indentation of 1 tab character but found 0  indent
  16:3   error  Expected indentation of 1 tab character but found 0  indent
  16:3   error  Unexpected console statement                         no-console
  16:17  error  Strings must use doublequote                         quotes
  16:72  error  Strings must use doublequote                         quotes
  22:3   error  Expected indentation of 1 tab character but found 0  indent
  22:16  error  Strings must use doublequote                         quotes
  22:28  error  Strings must use doublequote                         quotes
  23:3   error  Expected indentation of 1 tab character but found 0  indent
  24:5   error  Expected indentation of 1 tab character but found 0  indent
  24:19  error  Strings must use doublequote                         quotes
  24:42  error  Strings must use doublequote                         quotes
  26:5   error  Expected indentation of 1 tab character but found 0  indent
  26:18  error  Strings must use doublequote                         quotes
  26:41  error  Strings must use doublequote                         quotes
  27:7   error  Expected indentation of 1 tab character but found 0  indent

✖ 37 problems (37 errors, 0 warnings)


npm ERR! Linux 4.2.5-300.fc23.x86_64
npm ERR! argv "/home/robert/.nvm/versions/node/v4.0.0/bin/node" "/home/robert/.nvm/versions/node/v4.0.0/bin/npm" "run" "lint"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! getin-react@1.0.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getin-react@1.0.0 lint script 'eslint .'.
npm ERR! This is most likely a problem with the getin-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get their info via:
npm ERR!     npm owner ls getin-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robert/.meteor/getin-react/npm-debug.log


Ok some indentation errors... but those npm errors really confuse me . I was following your setup guide

**Comment by dferber90** [comment]
The error happens most likely because you misconfigured something.
You should probably add the `npm-container` folder to `.eslintignore`.
You can read up on ESLint [here](http://eslint.org/docs/user-guide/configuring).

This seems to neither be a problem of eslint-plugin-meteor, nor eslint itself.
I suggest closing the issue on ESLint, since they're busy guys and this has nothing to do with them.
