### ISSUE TITLE
Rule Proposal: Require absolute Imports

### ISSUE THREAD

**Issue by carlo-quinonez** [dferber90/eslint-plugin-meteor#784]
Since Meteor imports absolute references from the project root, they're easier to deal with and scan. In my meteor projects, the imports end up a mix of absolute and relative paths. It's hard to fight this because generally absolute paths in imports are a TERRIBLE idea, but it's just another great example of how Meteor turn problems on their heads sometimes.

```js
import module from '../../../api/database';
// vs
import module from '/imports/api/database';
```

Open to a PR?

**Comment by dferber90** [comment]
Thanks for your suggestion and for asking upfront. This rule doesn't sound like it would be related to `eslint-plugin-meteor` as it doesn't concern Meteor itself. It might be better suited somewhere else. You might be able to use [`no-relative-parent-imports`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-relative-parent-imports.md) from `eslint-plugin-import`.

<details>
<summary>Sidenote</summary>

I haven't used Meteor in quite a while, but Next.js has a similar feature. I usually end up with a mix of absolute and relative imports as well, but I don't see it as a problem.
 
Absolute imports are great when you are referring to another logical module, and relative is great when multiple things form one logical unit and are colocated.
 
It's a bit hard for me to judge as I'm not actively using Meteor anymore, but from my similar experience with Next.js I'd probably not want a rule like that.

</details>
