### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by jeffshaver** [dferber90/eslint-plugin-meteor#96]
Don't really know what the issue could be... It just doesn't work. It constantly tells me that Meteor is undefined (due to `no-undef: 2` being set in the standard config). But i put meteor in the plugins and i have the rules at the bottom. I have installed eslint/eslint-plugin-react/eslint-plugin-meteor and babel-eslint. Below is my `.eslintrc` file

```
{
  "parser": "babel-eslint",
  "globals": {
    "Async": false,
    "ReactMeteorData": false,
    "injectTapEventPlugin": false
  },
  "ecmaFeatures": {
    "jsx": true
  },
  "extends": "standard",
  "plugins": [
    "react",
    "meteor"
  ],
  "rules": {
    "array-bracket-spacing": [2, "never"],
    "no-trailing-spaces": [2, {"skipBlankLines": true}],
    "object-curly-spacing": [2, "never"],
    "padded-blocks": [2, "never"],
    "eol-last": 0,
    "react/jsx-closing-bracket-location": 2,
    "react/jsx-curly-spacing": 2,
    "react/jsx-indent-props": [2, 2],
    "react/jsx-key": 2,
    "react/jsx-max-props-per-line": [2, {"maximum": 1}],
    "react/jsx-no-duplicate-props": [2, {"ignoreCase": true}],
    "react/jsx-no-undef": 2,
    "react/jsx-pascal-case": 2,
    "react/jsx-sort-prop-types": [2, {"ignoreCase": true, "callbacksLast": true}],
    "react/jsx-sort-props": [2, {"ignoreCase": true, "callbacksLast": true}],
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/no-did-mount-set-state": 2,
    "react/no-did-update-set-state": 2,
    "react/no-direct-mutation-state": 2,
    "react/no-multi-comp": 2,
    "react/prefer-es6-class": 2,
    "react/prop-types": 2,
    "react/self-closing-comp": 2,
    "react/wrap-multilines": 2,

    "meteor/globals": 2,
    "meteor/core": 2,
    "meteor/pubsub": 2,
    "meteor/methods": 2,
    "meteor/check": 2,
    "meteor/connections": 2,
    "meteor/collections": 2,

    "meteor/audit-argument-checks": 2,
    "meteor/no-session": 2,
    "meteor/no-blaze-lifecycle-assignment": 2,
    "meteor/no-zero-timeout": 2,
    "meteor/blaze-consistent-eventmap-params": 2
  }
}
```

**Comment by dferber90** [comment]
I think there has been an update of ESLint which broke the way I was marking globals (such as `Meteor`) as defined. I haven't looked into that yet. I'm sorry for not communicating this.

Meteor will change again soon when it adds support for modules. Then this plugin will likely need a huge rewrite to account for the changes. I'm not using Meteor myself anymore right now, so I won't put in the time to rewrite it. I tried to get early feedback on how the module system will work, so I can prepare for it, but MDG didn't respond.

I'll add a note on the README.
The real value of this plugin would have been adding rules that make sure you are following best practices (eg avoid `Session`), but I didn't really get to that point. If somebody wants to take over development of this plugin, I'd be happy to explain how it works. Takes about 1-2 hours to understand it.

**Comment by dferber90** [comment]
This issue isn't fixed at the moment. I'll eventually rewrite eslint-plugin-meteor with a much narrower scope and less features, which will avoid this problem.
